name: Build workflow
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure CMake project
        run:  cmake -S . -B build

      - name: Build CMake project
        run: cmake --build build
