name: Build workflow
on:
  push:
    branches: [main]

jobs:
  Build stage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure CMake project
        run:  cmake -S . -B build

      - name: Build CMake project
        run: cmake --build build