name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.os }}

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/Release/mytestapp
            build/Release/mytestapp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        if: steps.create_release.outputs.upload_url != ''
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/Release/mytestapp
            build/Release/mytestapp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
